# Generated by Django 6.0.6 on 2026-06-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('mode', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('ESPECES', 'Espèces'), ('CARTE_BANCAIRE', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('montant_mga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (MGA)')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='orders.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
