# Generated by Django 6.0.6 on 2026-06-24 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('adresse_complete', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complément')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('est_par_defaut', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_livraison', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
                'ordering': ['-est_par_defaut', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('adresse_snapshot', models.CharField(blank=True, help_text="Copie textuelle de l'adresse au moment de la création", max_length=255, verbose_name='Snapshot adresse')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('PREPARATION', 'Préparation'), ('LIVRAISON_EN_COURS', 'Livraison en cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('total_mga', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (MGA)')),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.adresselivraison', verbose_name='Adresse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantite_vendue', models.PositiveIntegerField(verbose_name='Quantité vendue')),
                ('montant_total_mga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total (MGA)')),
                ('nom_produit', models.CharField(max_length=255, verbose_name='Nom produit')),
                ('prix_unitaire_mga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (MGA)')),
                ('nom_magasin', models.CharField(max_length=255, verbose_name='Nom magasin')),
                ('nom_client', models.CharField(max_length=255, verbose_name='Nom client')),
                ('reference_commande', models.CharField(max_length=50, verbose_name='Référence commande')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques', to='orders.commande', verbose_name='Commande')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.magasin', verbose_name='Magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Historique de vente',
                'verbose_name_plural': 'Historiques de vente',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire_mga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (MGA)')),
                ('nom_produit_snapshot', models.CharField(help_text='Nom du produit au moment de la création', max_length=255, verbose_name='Snapshot nom produit')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['date_creation'],
            },
        ),
    ]
