# Generated by Django 6.0.6 on 2026-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone'),
        ),
    ]
