# Generated by Django 6.0.6 on 2026-06-24 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('banniere', models.URLField(blank=True, default='', verbose_name='Bannière')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse')),
                ('horaires_ouverture', models.JSONField(blank=True, default=dict, verbose_name="Horaires d'ouverture")),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('nombre_etages', models.PositiveIntegerField(default=1, verbose_name="Nombre d'étages")),
                ('parking_disponible', models.BooleanField(default=False, verbose_name='Parking disponible')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Centre commercial',
                'verbose_name_plural': 'Centres commerciaux',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('banniere', models.URLField(blank=True, default='', verbose_name='Bannière')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse')),
                ('horaires_ouverture', models.JSONField(blank=True, default=dict, verbose_name="Horaires d'ouverture")),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('categorie', models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('VETEMENTS', 'Vêtements'), ('ELECTRONIQUE', 'Électronique'), ('RESTAURANT', 'Restaurant'), ('PHARMACIE', 'Pharmacie'), ('ARTISANAT', 'Artisanat'), ('BEAUTE', 'Beauté'), ('MAISON', 'Maison'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('etage', models.CharField(blank=True, default='', max_length=20, verbose_name='Étage')),
                ('numero_local', models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro de local')),
                ('centre_commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='places.centrecommercial', verbose_name='Centre commercial')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magasins', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
    ]
