# Generated by Django 6.0.6 on 2026-06-24 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('categorie', models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('VETEMENTS', 'Vêtements'), ('ELECTRONIQUE', 'Électronique'), ('ARTISANAT', 'Artisanat'), ('BEAUTE', 'Beauté'), ('MAISON', 'Maison'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('prix_mga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (MGA)')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('etat_stock', models.CharField(choices=[('EN_STOCK', 'En stock'), ('STOCK_FAIBLE', 'Stock faible'), ('RUPTURE_STOCK', 'Rupture de stock')], default='RUPTURE_STOCK', max_length=20, verbose_name='État du stock')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='places.magasin', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MediaProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('url_photo', models.URLField(verbose_name='URL de la photo')),
                ('legende', models.CharField(blank=True, default='', max_length=255, verbose_name='Légende')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='catalog.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Média produit',
                'verbose_name_plural': 'Médias produit',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
    ]
